version: '3.8'

services:
  backend:
    build:
      context: ./voting-system-api
      dockerfile: Dockerfile
    working_dir: /app/project
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    container_name: voting-backend
    volumes:
      - ./voting-system-api:/app

  frontend:
    build:
      context: ./voting-system-web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
